//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SampleApp.Acumatica {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ScreenSoap", Namespace="http://www.acumatica.com/generic/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Filter[]))]
    public partial class Screen : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetScenarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetBusinessDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetLocaleNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSchemaModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010ClearOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010GetProcessStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010GetSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010SetSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010ImportOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010ExportOperationCompleted;
        
        private System.Threading.SendOrPostCallback AR303010SubmitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Screen() {
            this.Url = global::SampleApp.Properties.Settings.Default.SampleApp_Acumatica_Screen;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetScenarioCompletedEventHandler GetScenarioCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event SetBusinessDateCompletedEventHandler SetBusinessDateCompleted;
        
        /// <remarks/>
        public event SetLocaleNameCompletedEventHandler SetLocaleNameCompleted;
        
        /// <remarks/>
        public event SetSchemaModeCompletedEventHandler SetSchemaModeCompleted;
        
        /// <remarks/>
        public event AR303010ClearCompletedEventHandler AR303010ClearCompleted;
        
        /// <remarks/>
        public event AR303010GetProcessStatusCompletedEventHandler AR303010GetProcessStatusCompleted;
        
        /// <remarks/>
        public event AR303010GetSchemaCompletedEventHandler AR303010GetSchemaCompleted;
        
        /// <remarks/>
        public event AR303010SetSchemaCompletedEventHandler AR303010SetSchemaCompleted;
        
        /// <remarks/>
        public event AR303010ImportCompletedEventHandler AR303010ImportCompleted;
        
        /// <remarks/>
        public event AR303010ExportCompletedEventHandler AR303010ExportCompleted;
        
        /// <remarks/>
        public event AR303010SubmitCompletedEventHandler AR303010SubmitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/GetScenario", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Command[] GetScenario(string scenario) {
            object[] results = this.Invoke("GetScenario", new object[] {
                        scenario});
            return ((Command[])(results[0]));
        }
        
        /// <remarks/>
        public void GetScenarioAsync(string scenario) {
            this.GetScenarioAsync(scenario, null);
        }
        
        /// <remarks/>
        public void GetScenarioAsync(string scenario, object userState) {
            if ((this.GetScenarioOperationCompleted == null)) {
                this.GetScenarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetScenarioOperationCompleted);
            }
            this.InvokeAsync("GetScenario", new object[] {
                        scenario}, this.GetScenarioOperationCompleted, userState);
        }
        
        private void OnGetScenarioOperationCompleted(object arg) {
            if ((this.GetScenarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetScenarioCompleted(this, new GetScenarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/Login", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginResult Login(string name, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        name,
                        password});
            return ((LoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string name, string password) {
            this.LoginAsync(name, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string name, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        name,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/SetBusinessDate", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetBusinessDate(System.DateTime date) {
            this.Invoke("SetBusinessDate", new object[] {
                        date});
        }
        
        /// <remarks/>
        public void SetBusinessDateAsync(System.DateTime date) {
            this.SetBusinessDateAsync(date, null);
        }
        
        /// <remarks/>
        public void SetBusinessDateAsync(System.DateTime date, object userState) {
            if ((this.SetBusinessDateOperationCompleted == null)) {
                this.SetBusinessDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetBusinessDateOperationCompleted);
            }
            this.InvokeAsync("SetBusinessDate", new object[] {
                        date}, this.SetBusinessDateOperationCompleted, userState);
        }
        
        private void OnSetBusinessDateOperationCompleted(object arg) {
            if ((this.SetBusinessDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetBusinessDateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/SetLocaleName", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetLocaleName(string localeName) {
            this.Invoke("SetLocaleName", new object[] {
                        localeName});
        }
        
        /// <remarks/>
        public void SetLocaleNameAsync(string localeName) {
            this.SetLocaleNameAsync(localeName, null);
        }
        
        /// <remarks/>
        public void SetLocaleNameAsync(string localeName, object userState) {
            if ((this.SetLocaleNameOperationCompleted == null)) {
                this.SetLocaleNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetLocaleNameOperationCompleted);
            }
            this.InvokeAsync("SetLocaleName", new object[] {
                        localeName}, this.SetLocaleNameOperationCompleted, userState);
        }
        
        private void OnSetLocaleNameOperationCompleted(object arg) {
            if ((this.SetLocaleNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetLocaleNameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/SetSchemaMode", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetSchemaMode(SchemaMode mode) {
            this.Invoke("SetSchemaMode", new object[] {
                        mode});
        }
        
        /// <remarks/>
        public void SetSchemaModeAsync(SchemaMode mode) {
            this.SetSchemaModeAsync(mode, null);
        }
        
        /// <remarks/>
        public void SetSchemaModeAsync(SchemaMode mode, object userState) {
            if ((this.SetSchemaModeOperationCompleted == null)) {
                this.SetSchemaModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSchemaModeOperationCompleted);
            }
            this.InvokeAsync("SetSchemaMode", new object[] {
                        mode}, this.SetSchemaModeOperationCompleted, userState);
        }
        
        private void OnSetSchemaModeOperationCompleted(object arg) {
            if ((this.SetSchemaModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSchemaModeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/Clear", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AR303010Clear() {
            this.Invoke("AR303010Clear", new object[0]);
        }
        
        /// <remarks/>
        public void AR303010ClearAsync() {
            this.AR303010ClearAsync(null);
        }
        
        /// <remarks/>
        public void AR303010ClearAsync(object userState) {
            if ((this.AR303010ClearOperationCompleted == null)) {
                this.AR303010ClearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010ClearOperationCompleted);
            }
            this.InvokeAsync("AR303010Clear", new object[0], this.AR303010ClearOperationCompleted, userState);
        }
        
        private void OnAR303010ClearOperationCompleted(object arg) {
            if ((this.AR303010ClearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010ClearCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/GetProcessStatus", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProcessStatusResult")]
        public ProcessResult AR303010GetProcessStatus() {
            object[] results = this.Invoke("AR303010GetProcessStatus", new object[0]);
            return ((ProcessResult)(results[0]));
        }
        
        /// <remarks/>
        public void AR303010GetProcessStatusAsync() {
            this.AR303010GetProcessStatusAsync(null);
        }
        
        /// <remarks/>
        public void AR303010GetProcessStatusAsync(object userState) {
            if ((this.AR303010GetProcessStatusOperationCompleted == null)) {
                this.AR303010GetProcessStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010GetProcessStatusOperationCompleted);
            }
            this.InvokeAsync("AR303010GetProcessStatus", new object[0], this.AR303010GetProcessStatusOperationCompleted, userState);
        }
        
        private void OnAR303010GetProcessStatusOperationCompleted(object arg) {
            if ((this.AR303010GetProcessStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010GetProcessStatusCompleted(this, new AR303010GetProcessStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/GetSchema", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetSchemaResult")]
        public AR303010Content AR303010GetSchema() {
            object[] results = this.Invoke("AR303010GetSchema", new object[0]);
            return ((AR303010Content)(results[0]));
        }
        
        /// <remarks/>
        public void AR303010GetSchemaAsync() {
            this.AR303010GetSchemaAsync(null);
        }
        
        /// <remarks/>
        public void AR303010GetSchemaAsync(object userState) {
            if ((this.AR303010GetSchemaOperationCompleted == null)) {
                this.AR303010GetSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010GetSchemaOperationCompleted);
            }
            this.InvokeAsync("AR303010GetSchema", new object[0], this.AR303010GetSchemaOperationCompleted, userState);
        }
        
        private void OnAR303010GetSchemaOperationCompleted(object arg) {
            if ((this.AR303010GetSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010GetSchemaCompleted(this, new AR303010GetSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/SetSchema", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AR303010SetSchema(AR303010Content schema) {
            this.Invoke("AR303010SetSchema", new object[] {
                        schema});
        }
        
        /// <remarks/>
        public void AR303010SetSchemaAsync(AR303010Content schema) {
            this.AR303010SetSchemaAsync(schema, null);
        }
        
        /// <remarks/>
        public void AR303010SetSchemaAsync(AR303010Content schema, object userState) {
            if ((this.AR303010SetSchemaOperationCompleted == null)) {
                this.AR303010SetSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010SetSchemaOperationCompleted);
            }
            this.InvokeAsync("AR303010SetSchema", new object[] {
                        schema}, this.AR303010SetSchemaOperationCompleted, userState);
        }
        
        private void OnAR303010SetSchemaOperationCompleted(object arg) {
            if ((this.AR303010SetSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010SetSchemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/Import", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ImportResult")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ImportResult")]
        public AR303010ImportResult[] AR303010Import(Command[] commands, Filter[] filters, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            object[] results = this.Invoke("AR303010Import", new object[] {
                        commands,
                        filters,
                        data,
                        includedHeaders,
                        breakOnError,
                        breakOnIncorrectTarget});
            return ((AR303010ImportResult[])(results[0]));
        }
        
        /// <remarks/>
        public void AR303010ImportAsync(Command[] commands, Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget) {
            this.AR303010ImportAsync(commands, filters, data, includedHeaders, breakOnError, breakOnIncorrectTarget, null);
        }
        
        /// <remarks/>
        public void AR303010ImportAsync(Command[] commands, Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget, object userState) {
            if ((this.AR303010ImportOperationCompleted == null)) {
                this.AR303010ImportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010ImportOperationCompleted);
            }
            this.InvokeAsync("AR303010Import", new object[] {
                        commands,
                        filters,
                        data,
                        includedHeaders,
                        breakOnError,
                        breakOnIncorrectTarget}, this.AR303010ImportOperationCompleted, userState);
        }
        
        private void OnAR303010ImportOperationCompleted(object arg) {
            if ((this.AR303010ImportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010ImportCompleted(this, new AR303010ImportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/Export", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ExportResult")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] AR303010Export(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            object[] results = this.Invoke("AR303010Export", new object[] {
                        commands,
                        filters,
                        topCount,
                        includeHeaders,
                        breakOnError});
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void AR303010ExportAsync(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError) {
            this.AR303010ExportAsync(commands, filters, topCount, includeHeaders, breakOnError, null);
        }
        
        /// <remarks/>
        public void AR303010ExportAsync(Command[] commands, Filter[] filters, int topCount, bool includeHeaders, bool breakOnError, object userState) {
            if ((this.AR303010ExportOperationCompleted == null)) {
                this.AR303010ExportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010ExportOperationCompleted);
            }
            this.InvokeAsync("AR303010Export", new object[] {
                        commands,
                        filters,
                        topCount,
                        includeHeaders,
                        breakOnError}, this.AR303010ExportOperationCompleted, userState);
        }
        
        private void OnAR303010ExportOperationCompleted(object arg) {
            if ((this.AR303010ExportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010ExportCompleted(this, new AR303010ExportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.acumatica.com/generic/AR303010/Submit", RequestNamespace="http://www.acumatica.com/generic/", ResponseNamespace="http://www.acumatica.com/generic/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("SubmitResult")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Content")]
        public AR303010Content[] AR303010Submit(Command[] commands) {
            object[] results = this.Invoke("AR303010Submit", new object[] {
                        commands});
            return ((AR303010Content[])(results[0]));
        }
        
        /// <remarks/>
        public void AR303010SubmitAsync(Command[] commands) {
            this.AR303010SubmitAsync(commands, null);
        }
        
        /// <remarks/>
        public void AR303010SubmitAsync(Command[] commands, object userState) {
            if ((this.AR303010SubmitOperationCompleted == null)) {
                this.AR303010SubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAR303010SubmitOperationCompleted);
            }
            this.InvokeAsync("AR303010Submit", new object[] {
                        commands}, this.AR303010SubmitOperationCompleted, userState);
        }
        
        private void OnAR303010SubmitOperationCompleted(object arg) {
            if ((this.AR303010SubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AR303010SubmitCompleted(this, new AR303010SubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Answer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Action))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Key))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EveryValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Command {
        
        private string fieldNameField;
        
        private string objectNameField;
        
        private string valueField;
        
        private bool commitField;
        
        private bool ignoreErrorField;
        
        private Command linkedCommandField;
        
        private ElementDescriptor descriptorField;
        
        public Command() {
            this.commitField = false;
            this.ignoreErrorField = false;
        }
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Commit {
            get {
                return this.commitField;
            }
            set {
                this.commitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreError {
            get {
                return this.ignoreErrorField;
            }
            set {
                this.ignoreErrorField = value;
            }
        }
        
        /// <remarks/>
        public Command LinkedCommand {
            get {
                return this.linkedCommandField;
            }
            set {
                this.linkedCommandField = value;
            }
        }
        
        /// <remarks/>
        public ElementDescriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class ElementDescriptor {
        
        private string displayNameField;
        
        private bool isDisabledField;
        
        private bool isRequiredField;
        
        private ElementTypes elementTypeField;
        
        private int lengthLimitField;
        
        private string inputMaskField;
        
        private string displayRulesField;
        
        private string[] allowedValuesField;
        
        public ElementDescriptor() {
            this.isDisabledField = false;
            this.isRequiredField = false;
            this.elementTypeField = ElementTypes.String;
            this.lengthLimitField = 0;
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDisabled {
            get {
                return this.isDisabledField;
            }
            set {
                this.isDisabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ElementTypes.String)]
        public ElementTypes ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int LengthLimit {
            get {
                return this.lengthLimitField;
            }
            set {
                this.lengthLimitField = value;
            }
        }
        
        /// <remarks/>
        public string InputMask {
            get {
                return this.inputMaskField;
            }
            set {
                this.inputMaskField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayRules {
            get {
                return this.displayRulesField;
            }
            set {
                this.displayRulesField = value;
            }
        }
        
        /// <remarks/>
        public string[] AllowedValues {
            get {
                return this.allowedValuesField;
            }
            set {
                this.allowedValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum ElementTypes {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        AsciiString,
        
        /// <remarks/>
        StringSelector,
        
        /// <remarks/>
        ExplicitSelector,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Option,
        
        /// <remarks/>
        WideOption,
        
        /// <remarks/>
        Calendar,
        
        /// <remarks/>
        Action,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010ImportResult {
        
        private bool processedField;
        
        private string errorField;
        
        private AR303010PrimaryKey keysField;
        
        /// <remarks/>
        public bool Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PrimaryKey Keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PrimaryKey {
        
        private Value customerField;
        
        private Value tokenIDField;
        
        /// <remarks/>
        public Value Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Value TokenID {
            get {
                return this.tokenIDField;
            }
            set {
                this.tokenIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Value : Field {
        
        private string messageField;
        
        private bool isErrorField;
        
        public Value() {
            this.isErrorField = false;
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Field : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Attachment : Field {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Filter {
        
        private Field fieldField;
        
        private FilterCondition conditionField;
        
        private object valueField;
        
        private object value2Field;
        
        private int openBracketsField;
        
        private int closeBracketsField;
        
        private FilterOperator operatorField;
        
        /// <remarks/>
        public Field Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public FilterCondition Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public object Value2 {
            get {
                return this.value2Field;
            }
            set {
                this.value2Field = value;
            }
        }
        
        /// <remarks/>
        public int OpenBrackets {
            get {
                return this.openBracketsField;
            }
            set {
                this.openBracketsField = value;
            }
        }
        
        /// <remarks/>
        public int CloseBrackets {
            get {
                return this.closeBracketsField;
            }
            set {
                this.closeBracketsField = value;
            }
        }
        
        /// <remarks/>
        public FilterOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum FilterCondition {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Contain,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        NotContain,
        
        /// <remarks/>
        Between,
        
        /// <remarks/>
        IsNull,
        
        /// <remarks/>
        IsNotNull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum FilterOperator {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoContactInformationServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class DeleteRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Answer : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoContactInformation {
        
        private string displayNameField;
        
        private Field firstNameField;
        
        private Field lastNameField;
        
        private Field phone1Field;
        
        private Field phone2Field;
        
        private Field faxField;
        
        private Field emailField;
        
        private Field webField;
        
        private AR303010BillingInfoContactInformationServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public Field LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public Field Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public Field Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public Field Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public Field Web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoContactInformationServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoAddressServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoAddress {
        
        private string displayNameField;
        
        private Field validatedField;
        
        private Field addressLine1Field;
        
        private Field addressLine2Field;
        
        private Field cityField;
        
        private Field countryField;
        
        private Field stateField;
        
        private Field postalCodeField;
        
        private AR303010BillingInfoAddressServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Validated {
            get {
                return this.validatedField;
            }
            set {
                this.validatedField = value;
            }
        }
        
        /// <remarks/>
        public Field AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public Field AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public Field City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public Field Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public Field State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public Field PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoAddressServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PaymentMethodDetailsServiceCommands {
        
        private Key keyDescriptionField;
        
        private NewRow newRowField;
        
        private RowNumber rowNumberField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        /// <remarks/>
        public Key KeyDescription {
            get {
                return this.keyDescriptionField;
            }
            set {
                this.keyDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public NewRow NewRow {
            get {
                return this.newRowField;
            }
            set {
                this.newRowField = value;
            }
        }
        
        /// <remarks/>
        public RowNumber RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Key : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class NewRow : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class RowNumber : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PaymentMethodDetails {
        
        private string displayNameField;
        
        private Field descriptionField;
        
        private Field valueField;
        
        private AR303010PaymentMethodDetailsServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Field Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PaymentMethodDetailsServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PaymentMethodSelectionInputModeServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PaymentMethodSelectionInputMode {
        
        private string displayNameField;
        
        private Field inputModeField;
        
        private AR303010PaymentMethodSelectionInputModeServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field InputMode {
            get {
                return this.inputModeField;
            }
            set {
                this.inputModeField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PaymentMethodSelectionInputModeServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoAddressSameAsMainServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoAddressSameAsMain {
        
        private string displayNameField;
        
        private Field sameAsMainField;
        
        private AR303010BillingInfoAddressSameAsMainServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field SameAsMain {
            get {
                return this.sameAsMainField;
            }
            set {
                this.sameAsMainField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoAddressSameAsMainServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoContactInformationSameAsMainServiceCommands {
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010BillingInfoContactInformationSameAsMain {
        
        private string displayNameField;
        
        private Field sameAsMainField;
        
        private AR303010BillingInfoContactInformationSameAsMainServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field SameAsMain {
            get {
                return this.sameAsMainField;
            }
            set {
                this.sameAsMainField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoContactInformationSameAsMainServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PaymentMethodSelectionServiceCommands {
        
        private Parameter parameterBAccountIDField;
        
        private Key keyCustomerField;
        
        private EveryValue everyCustomerField;
        
        private Key keyTokenIDField;
        
        private EveryValue everyTokenIDField;
        
        private Field filterAddressLine1Field;
        
        private Field filterAddressLine2Field;
        
        private Field filterPostalCodeField;
        
        private Field filterPhone1Field;
        
        private Field filterCityField;
        
        private Field filterCountryField;
        
        private Field filterTaxRegistrationIDField;
        
        private Field filterCurrencyIDField;
        
        private Field filterAttentionField;
        
        private Field filterCustomerClassField;
        
        private Field filterStatusField;
        
        private DeleteRow deleteRowField;
        
        private Answer dialogAnswerField;
        
        private Attachment attachmentField;
        
        /// <remarks/>
        public Parameter ParameterBAccountID {
            get {
                return this.parameterBAccountIDField;
            }
            set {
                this.parameterBAccountIDField = value;
            }
        }
        
        /// <remarks/>
        public Key KeyCustomer {
            get {
                return this.keyCustomerField;
            }
            set {
                this.keyCustomerField = value;
            }
        }
        
        /// <remarks/>
        public EveryValue EveryCustomer {
            get {
                return this.everyCustomerField;
            }
            set {
                this.everyCustomerField = value;
            }
        }
        
        /// <remarks/>
        public Key KeyTokenID {
            get {
                return this.keyTokenIDField;
            }
            set {
                this.keyTokenIDField = value;
            }
        }
        
        /// <remarks/>
        public EveryValue EveryTokenID {
            get {
                return this.everyTokenIDField;
            }
            set {
                this.everyTokenIDField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterAddressLine1 {
            get {
                return this.filterAddressLine1Field;
            }
            set {
                this.filterAddressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public Field FilterAddressLine2 {
            get {
                return this.filterAddressLine2Field;
            }
            set {
                this.filterAddressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public Field FilterPostalCode {
            get {
                return this.filterPostalCodeField;
            }
            set {
                this.filterPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterPhone1 {
            get {
                return this.filterPhone1Field;
            }
            set {
                this.filterPhone1Field = value;
            }
        }
        
        /// <remarks/>
        public Field FilterCity {
            get {
                return this.filterCityField;
            }
            set {
                this.filterCityField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterCountry {
            get {
                return this.filterCountryField;
            }
            set {
                this.filterCountryField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterTaxRegistrationID {
            get {
                return this.filterTaxRegistrationIDField;
            }
            set {
                this.filterTaxRegistrationIDField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterCurrencyID {
            get {
                return this.filterCurrencyIDField;
            }
            set {
                this.filterCurrencyIDField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterAttention {
            get {
                return this.filterAttentionField;
            }
            set {
                this.filterAttentionField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterCustomerClass {
            get {
                return this.filterCustomerClassField;
            }
            set {
                this.filterCustomerClassField = value;
            }
        }
        
        /// <remarks/>
        public Field FilterStatus {
            get {
                return this.filterStatusField;
            }
            set {
                this.filterStatusField = value;
            }
        }
        
        /// <remarks/>
        public DeleteRow DeleteRow {
            get {
                return this.deleteRowField;
            }
            set {
                this.deleteRowField = value;
            }
        }
        
        /// <remarks/>
        public Answer DialogAnswer {
            get {
                return this.dialogAnswerField;
            }
            set {
                this.dialogAnswerField = value;
            }
        }
        
        /// <remarks/>
        public Attachment Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Parameter : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class EveryValue : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010PaymentMethodSelection {
        
        private string displayNameField;
        
        private Field customerField;
        
        private Field paymentMethodField;
        
        private Field hasBillingInfoField;
        
        private Field tokenIDField;
        
        private Field activeField;
        
        private Field procCenterIDField;
        
        private Field customerProfileIDField;
        
        private Field cashAccountField;
        
        private Field cardAccountNoField;
        
        private Field noteTextField;
        
        private AR303010PaymentMethodSelectionServiceCommands serviceCommandsField;
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public Field Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Field PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public Field HasBillingInfo {
            get {
                return this.hasBillingInfoField;
            }
            set {
                this.hasBillingInfoField = value;
            }
        }
        
        /// <remarks/>
        public Field TokenID {
            get {
                return this.tokenIDField;
            }
            set {
                this.tokenIDField = value;
            }
        }
        
        /// <remarks/>
        public Field Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public Field ProcCenterID {
            get {
                return this.procCenterIDField;
            }
            set {
                this.procCenterIDField = value;
            }
        }
        
        /// <remarks/>
        public Field CustomerProfileID {
            get {
                return this.customerProfileIDField;
            }
            set {
                this.customerProfileIDField = value;
            }
        }
        
        /// <remarks/>
        public Field CashAccount {
            get {
                return this.cashAccountField;
            }
            set {
                this.cashAccountField = value;
            }
        }
        
        /// <remarks/>
        public Field CardAccountNo {
            get {
                return this.cardAccountNoField;
            }
            set {
                this.cardAccountNoField = value;
            }
        }
        
        /// <remarks/>
        public Field NoteText {
            get {
                return this.noteTextField;
            }
            set {
                this.noteTextField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PaymentMethodSelectionServiceCommands ServiceCommands {
            get {
                return this.serviceCommandsField;
            }
            set {
                this.serviceCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010Actions {
        
        private Action saveField;
        
        private Action cancelField;
        
        private Action insertField;
        
        private Action copyDocumentCopyPasteField;
        
        private Action pasteDocumentCopyPasteField;
        
        private Action saveTemplateCopyPasteField;
        
        private Action deleteField;
        
        private Action firstField;
        
        private Action previousField;
        
        private Action nextField;
        
        private Action lastField;
        
        private Action viewBillAddressOnMapField;
        
        private Action validateAddressesField;
        
        private Action createCCPaymentMethodHFField;
        
        private Action syncCCPaymentMethodsField;
        
        private Action manageCCPaymentMethodHFField;
        
        /// <remarks/>
        public Action Save {
            get {
                return this.saveField;
            }
            set {
                this.saveField = value;
            }
        }
        
        /// <remarks/>
        public Action Cancel {
            get {
                return this.cancelField;
            }
            set {
                this.cancelField = value;
            }
        }
        
        /// <remarks/>
        public Action Insert {
            get {
                return this.insertField;
            }
            set {
                this.insertField = value;
            }
        }
        
        /// <remarks/>
        public Action CopyDocumentCopyPaste {
            get {
                return this.copyDocumentCopyPasteField;
            }
            set {
                this.copyDocumentCopyPasteField = value;
            }
        }
        
        /// <remarks/>
        public Action PasteDocumentCopyPaste {
            get {
                return this.pasteDocumentCopyPasteField;
            }
            set {
                this.pasteDocumentCopyPasteField = value;
            }
        }
        
        /// <remarks/>
        public Action SaveTemplateCopyPaste {
            get {
                return this.saveTemplateCopyPasteField;
            }
            set {
                this.saveTemplateCopyPasteField = value;
            }
        }
        
        /// <remarks/>
        public Action Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        public Action First {
            get {
                return this.firstField;
            }
            set {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        public Action Previous {
            get {
                return this.previousField;
            }
            set {
                this.previousField = value;
            }
        }
        
        /// <remarks/>
        public Action Next {
            get {
                return this.nextField;
            }
            set {
                this.nextField = value;
            }
        }
        
        /// <remarks/>
        public Action Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        public Action ViewBillAddressOnMap {
            get {
                return this.viewBillAddressOnMapField;
            }
            set {
                this.viewBillAddressOnMapField = value;
            }
        }
        
        /// <remarks/>
        public Action ValidateAddresses {
            get {
                return this.validateAddressesField;
            }
            set {
                this.validateAddressesField = value;
            }
        }
        
        /// <remarks/>
        public Action CreateCCPaymentMethodHF {
            get {
                return this.createCCPaymentMethodHFField;
            }
            set {
                this.createCCPaymentMethodHFField = value;
            }
        }
        
        /// <remarks/>
        public Action SyncCCPaymentMethods {
            get {
                return this.syncCCPaymentMethodsField;
            }
            set {
                this.syncCCPaymentMethodsField = value;
            }
        }
        
        /// <remarks/>
        public Action ManageCCPaymentMethodHF {
            get {
                return this.manageCCPaymentMethodHFField;
            }
            set {
                this.manageCCPaymentMethodHFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class Action : Command {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class AR303010Content {
        
        private AR303010Actions actionsField;
        
        private AR303010PaymentMethodSelection paymentMethodSelectionField;
        
        private AR303010BillingInfoContactInformationSameAsMain billingInfoContactInformationSameAsMainField;
        
        private AR303010BillingInfoAddressSameAsMain billingInfoAddressSameAsMainField;
        
        private AR303010PaymentMethodSelectionInputMode paymentMethodSelectionInputModeField;
        
        private AR303010PaymentMethodDetails paymentMethodDetailsField;
        
        private AR303010BillingInfoAddress billingInfoAddressField;
        
        private AR303010BillingInfoContactInformation billingInfoContactInformationField;
        
        /// <remarks/>
        public AR303010Actions Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PaymentMethodSelection PaymentMethodSelection {
            get {
                return this.paymentMethodSelectionField;
            }
            set {
                this.paymentMethodSelectionField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoContactInformationSameAsMain BillingInfoContactInformationSameAsMain {
            get {
                return this.billingInfoContactInformationSameAsMainField;
            }
            set {
                this.billingInfoContactInformationSameAsMainField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoAddressSameAsMain BillingInfoAddressSameAsMain {
            get {
                return this.billingInfoAddressSameAsMainField;
            }
            set {
                this.billingInfoAddressSameAsMainField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PaymentMethodSelectionInputMode PaymentMethodSelectionInputMode {
            get {
                return this.paymentMethodSelectionInputModeField;
            }
            set {
                this.paymentMethodSelectionInputModeField = value;
            }
        }
        
        /// <remarks/>
        public AR303010PaymentMethodDetails PaymentMethodDetails {
            get {
                return this.paymentMethodDetailsField;
            }
            set {
                this.paymentMethodDetailsField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoAddress BillingInfoAddress {
            get {
                return this.billingInfoAddressField;
            }
            set {
                this.billingInfoAddressField = value;
            }
        }
        
        /// <remarks/>
        public AR303010BillingInfoContactInformation BillingInfoContactInformation {
            get {
                return this.billingInfoContactInformationField;
            }
            set {
                this.billingInfoContactInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class ProcessResult {
        
        private ProcessStatus statusField;
        
        private int secondsField;
        
        private string messageField;
        
        /// <remarks/>
        public ProcessStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum ProcessStatus {
        
        /// <remarks/>
        NotExists,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public partial class LoginResult {
        
        private ErrorCode codeField;
        
        private string messageField;
        
        private string sessionField;
        
        /// <remarks/>
        public ErrorCode Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum ErrorCode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        INVALID_CREDENTIALS,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        INVALID_API_VERSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/generic/")]
    public enum SchemaMode {
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Detailed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetScenarioCompletedEventHandler(object sender, GetScenarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetScenarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetScenarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Command[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Command[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetBusinessDateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetLocaleNameCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SetSchemaModeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010ClearCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010GetProcessStatusCompletedEventHandler(object sender, AR303010GetProcessStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AR303010GetProcessStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AR303010GetProcessStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcessResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcessResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010GetSchemaCompletedEventHandler(object sender, AR303010GetSchemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AR303010GetSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AR303010GetSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AR303010Content Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AR303010Content)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010SetSchemaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010ImportCompletedEventHandler(object sender, AR303010ImportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AR303010ImportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AR303010ImportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AR303010ImportResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AR303010ImportResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010ExportCompletedEventHandler(object sender, AR303010ExportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AR303010ExportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AR303010ExportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AR303010SubmitCompletedEventHandler(object sender, AR303010SubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AR303010SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AR303010SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AR303010Content[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AR303010Content[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591